
title: Arrow of Code
subtitle: Scribblings from a physics nerd...
author: Ravi Shankar
email: wafflespeanut@gmail.com
description:

url: "https://blog.waffles.space"
twitter_username: wafflespeanut
github_username:  wafflespeanut

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
timezone: Asia/Kolkata
permalink: /:year/:month/:day/:title/

google_analytics: UA-64401105-1
